import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/headerPage";
import Search from "@/components/SearchPage";
const inter = Inter({ subsets: ["latin"] });
export const metadata = {
  title: "Zillow",
  description: "Generated by create next app",
};
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {children}
        </body>
    </html>
  );
}
